extern crate cbindgen;

use std::env;
use std::path::PathBuf;

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let package_name = env::var("CARGO_PKG_NAME").unwrap();

    let workspace_root = PathBuf::from(&crate_dir).parent().unwrap().to_path_buf();
    let output_file = workspace_root.join(format!("{}.h", package_name));

    println!(
        "cargo:warning=Generating C header for '{}' at: {}",
        package_name,
        output_file.display()
    );

    let config_path = PathBuf::from(&crate_dir).join("cbindgen.toml");
    let config = if config_path.exists() {
        cbindgen::Config::from_file(&config_path)
            .expect("Unable to load cbindgen.toml from bedrock_cracker directory")
    } else {
        let mut c = cbindgen::Config::default();
        c.language = cbindgen::Language::C;
        c.include_guard = Some(format!("{}_H", package_name.to_uppercase().replace("-", "_")));
        c.header = Some(format!("/* Generated by cbindgen for {} */", package_name));
        c.usize_is_size_t = true;
        c.enumeration.prefix_with_name = true;
        c
    };

    cbindgen::Builder::new()
        .with_crate(&crate_dir)
        .with_config(config)
        .generate()
        .expect("Unable to generate C bindings")
        .write_to_file(&output_file);

    println!("cargo:rerun-if-changed=src/lib.rs");
    println!("cargo:rerun-if-changed=src/block_data.rs");
    println!("cargo:rerun-if-changed=src/layer.rs");
    println!("cargo:rerun-if-changed=src/raw_data/mod.rs");
    println!("cargo:rerun-if-changed=src/raw_data/block.rs");
    println!("cargo:rerun-if-changed=src/raw_data/block_type.rs");
    println!("cargo:rerun-if-changed=src/raw_data/modes.rs");
    println!("cargo:rerun-if-changed=src/raw_data/sender.rs");
    if config_path.exists() {
        println!("cargo:rerun-if-changed=cbindgen.toml");
    }
}